import random

def CowBull():
    try:
        count = 0
        #generat a random 4 digit list
        secret= [random.randint(0,9) for _ in range(4)]
        
        while True:
            #validation
            guess = input("Please enter a four-digit number: ")
            if not guess.isdigit():
                print("please Enter only Digit")
                continue
            if len(guess) != 4:
                print("Please Enter Only 4 Digit")
                continue
            
            #convert string value to integer
            guess_list = [int(i) for i in guess]

            temp_secret = secret.copy()
            print('temp_secret:',temp_secret)

            cow = 0
            bull = 0

            for i in range(0,4):
                if guess_list[i] == temp_secret[i]:
                    cow += 1
                    temp_secret[i]=guess_list[i]=None
            
            for i in range(0,4):
                if guess_list[i] in temp_secret and guess_list[i] is not None:
                    index = temp_secret.index(guess_list[i])
                    if index != i:
                        bull += 1
                        temp_secret[index] = None

            print(f"{cow} cow, {bull} bull")
            
            count += 1
            if cow == 4:
                print(f'number generated by the computer is {secret}')
                print('You Won')
                print('Count Of Try :',count)
                break
            
    except Exception as e:
        print(str(e))
CowBull()